name: Checkout Example

on:
  workflow_dispatch:

jobs:
  checkout-example:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify directory contents
        run: ls -alhR
