name: Complete Example

on:
  workflow_dispatch:

jobs:
  complete-example:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - run: npm install

      - run: npm run build --if-present

      - name: Run tests
        run: npm test --coverage

      - name: Upload test report
        with:
          name: test-report
          path: junit.xml

      - name: Verify directory contents
        run: ls -alhR

      - name: Bundle app files + node_modules into zip
        run: zip -r app_bundle.zip app node_modules

      - name: Better Test Reports Action
        # You may pin to the exact commit or the version.
        # uses: mridang/action-test-reporter@720c9c56f73e527681bcb30c33da4ccd62bf70fb
        uses: mridang/action-test-reporter@v1.3.0
        with:
          # GitHub token used to authenticate API requests. Required for checking status checks and publishing releases. Use `secrets.GITHUB_TOKEN` or a PAT with elevated scopes if needed.
          github-token: secrets.GITHUB_TOKEN
          # The directory where your project is located, used as the base for making file paths in the report relative.
          working-directory: .
          # The path to the single code coverage report file you want to parse (e.g., 'build/reports/clover.xml').
          coverage-file: .github/workflows/complete.yml
          # Set to `true` to upload the generated coverage report as a workflow artifact. If omitted or left empty, this defaults to `true`. Set to `false` to disable artifact upload.
          upload-coverage-report: true

      -
          name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
            context: .
            push: true
            tags: user/app:latest
