name: Dependencies Example

on:
  workflow_dispatch:

jobs:
  dependencies-example:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js (NPM)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Verify directory contents
        run: ls -alhR
